import type {
  Property,
  Lead,
  Visitor,
  CaptureService,
  FloorPlan,
  BookingSlot,
  PropertyMerge,
  CrossPlatformShare,
  WooCommerceProduct,
  Model3DAsset,
  SceneTypeConfig,
  TechnicianProfile,
  CSSCustomization,
} from "./types"

export const mockProperties: Property[] = [
  {
    id: "prop-001",
    name: "Luxury Downtown Penthouse",
    address: "123 Park Avenue, New York, NY 10022",
    price: 4500000,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 4200,
    description: "Stunning penthouse with panoramic city views, high-end finishes, and smart home automation.",
    images: [
      "/luxury-penthouse-living-room.png",
      "/modern-kitchen-with-marble-counters.jpg",
      "/master-bedroom-with-city-view.jpg",
    ],
    thumbnail: "/penthouse-exterior.jpg",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-10-20"),
    isFavorite: false,
    tags: ["luxury", "penthouse", "city-view", "smart-home"],
    floorPlanId: "floor-001",
    dayNightImages: {
      day: "/luxury-penthouse-day.jpg",
      night: "/luxury-penthouse-night.jpg",
    },
    branding: {
      primaryColor: "#1a3a52",
      secondaryColor: "#d4af37",
      logo: "/baladshelter-logo.jpg",
      companyName: "BaladShelter",
      contactEmail: "info@baladshelter.com",
      contactPhone: "+1 (555) 123-4567",
      whiteLabelMode: false,
    },
    scenes: [
      {
        id: "scene-001",
        name: "Living Room",
        imageUrl: "/luxury-penthouse-living-room-360.jpg",
        thumbnail: "/luxury-penthouse-living-room.png",
        viewCount: 145,
        dwellTime: 45,
        hotspots: [
          {
            id: "hotspot-001",
            x: 45,
            y: 50,
            type: "info",
            title: "Floor-to-Ceiling Windows",
            description: "Premium glass with UV protection and smart tinting",
            clickCount: 23,
          },
          {
            id: "hotspot-002",
            x: 70,
            y: 60,
            type: "video",
            title: "Smart Home Demo",
            description: "Watch the smart home automation in action",
            mediaUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
            clickCount: 15,
          },
          {
            id: "hotspot-003",
            x: 30,
            y: 40,
            type: "cta",
            title: "Schedule Tour",
            description: "Book an in-person viewing",
            clickCount: 8,
          },
        ],
        measurements: [],
        annotations: [],
        order: 1,
      },
      {
        id: "scene-002",
        name: "Master Bedroom",
        imageUrl: "/luxury-master-bedroom-with-city-view.jpg",
        thumbnail: "/master-bedroom-with-city-view.jpg",
        viewCount: 98,
        dwellTime: 32,
        hotspots: [
          {
            id: "hotspot-004",
            x: 50,
            y: 45,
            type: "link",
            title: "Back to Living Room",
            description: "Return to main area",
            targetSceneId: "scene-001",
            clickCount: 12,
          },
          {
            id: "hotspot-005",
            x: 60,
            y: 55,
            type: "audio",
            title: "Room Audio System",
            description: "Premium Bose sound system",
            mediaUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
            clickCount: 5,
          },
        ],
        measurements: [],
        annotations: [],
        order: 2,
      },
      {
        id: "scene-003",
        name: "Kitchen",
        imageUrl: "/modern-luxury-kitchen-with-marble.jpg",
        thumbnail: "/modern-kitchen-with-marble-counters.jpg",
        viewCount: 87,
        dwellTime: 28,
        hotspots: [
          {
            id: "hotspot-006",
            x: 40,
            y: 50,
            type: "image",
            title: "Marble Countertops",
            description: "Italian marble with professional appliances",
            mediaUrl: "/modern-kitchen-with-marble-counters.jpg",
            clickCount: 18,
          },
        ],
        measurements: [],
        annotations: [],
        order: 3,
      },
    ],
    stats: {
      totalVisits: 342,
      uniqueVisitors: 287,
      avgDuration: 8.5,
      conversionRate: 12.5,
      leadsGenerated: 34,
      lastUpdated: new Date(),
      hotspotEngagement: {
        "hotspot-001": 23,
        "hotspot-002": 15,
        "hotspot-003": 8,
      },
      scenePopularity: {
        "scene-001": 145,
        "scene-002": 98,
        "scene-003": 87,
      },
    },
  },
  {
    id: "prop-002",
    name: "Modern Suburban Family Home",
    address: "456 Oak Street, Austin, TX 78704",
    price: 850000,
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 3100,
    description: "Contemporary home with open floor plan, energy-efficient features, and beautiful backyard.",
    images: ["/modern-suburban-home-exterior.jpg", "/open-concept-living-area.jpg", "/backyard-with-pool.png"],
    thumbnail: "/suburban-home-front.jpg",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-10-18"),
    isFavorite: false,
    tags: ["family-home", "suburban", "pool", "modern"],
    floorPlanId: "floor-002",
    dayNightImages: {
      day: "/modern-suburban-day.jpg",
      night: "/modern-suburban-night.jpg",
    },
    branding: {
      primaryColor: "#1a3a52",
      secondaryColor: "#d4af37",
      logo: "/baladshelter-logo.jpg",
      companyName: "BaladShelter",
      contactEmail: "info@baladshelter.com",
      contactPhone: "+1 (555) 123-4567",
      whiteLabelMode: false,
    },
    scenes: [
      {
        id: "scene-004",
        name: "Foyer",
        imageUrl: "/modern-home-foyer-entrance.jpg",
        thumbnail: "/modern-home-foyer-entrance.jpg",
        viewCount: 76,
        dwellTime: 15,
        hotspots: [],
        measurements: [],
        annotations: [],
        order: 1,
      },
      {
        id: "scene-005",
        name: "Living Area",
        imageUrl: "/open-concept-living-room.jpg",
        thumbnail: "/open-concept-living-room.jpg",
        viewCount: 92,
        dwellTime: 38,
        hotspots: [
          {
            id: "hotspot-007",
            x: 50,
            y: 50,
            type: "info",
            title: "Open Concept Design",
            description: "Seamless flow between living and dining areas",
            clickCount: 14,
          },
        ],
        measurements: [],
        annotations: [],
        order: 2,
      },
      {
        id: "scene-006",
        name: "Backyard",
        imageUrl: "/backyard-with-pool.png",
        thumbnail: "/backyard-with-pool.png",
        viewCount: 68,
        dwellTime: 25,
        hotspots: [
          {
            id: "hotspot-008",
            x: 45,
            y: 60,
            type: "info",
            title: "Resort-Style Pool",
            description: "Heated pool with spa jets and waterfall",
            clickCount: 11,
          },
        ],
        measurements: [],
        annotations: [],
        order: 3,
      },
    ],
    stats: {
      totalVisits: 156,
      uniqueVisitors: 128,
      avgDuration: 6.2,
      conversionRate: 8.3,
      leadsGenerated: 12,
      lastUpdated: new Date(),
      hotspotEngagement: {
        "hotspot-007": 14,
        "hotspot-008": 11,
      },
      scenePopularity: {
        "scene-004": 76,
        "scene-005": 92,
        "scene-006": 68,
      },
    },
  },
]

export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    propertyId: "prop-001",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1 (555) 987-6543",
    message: "Very interested in the penthouse. Would like to schedule a viewing.",
    visitDuration: 12.5,
    scenesViewed: 3,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    status: "qualified",
    notes: "High-value prospect, serious buyer",
    source: "virtual-tour",
  },
  {
    id: "lead-002",
    propertyId: "prop-001",
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    phone: "+1 (555) 234-5678",
    message: "Interested in learning more about the property.",
    visitDuration: 8.2,
    scenesViewed: 2,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    status: "contacted",
    notes: "Relocating from California",
    source: "virtual-tour",
  },
  {
    id: "lead-003",
    propertyId: "prop-002",
    name: "Alicia Brown",
    email: "alicia.brown@email.com",
    phone: "+1 (555) 765-4321",
    message: "Interested in backyard amenities.",
    visitDuration: 6.8,
    scenesViewed: 2,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    status: "new",
    notes: "Prefers weekend viewings",
    source: "virtual-tour",
  },
]

export const mockVisitors: Visitor[] = [
  {
    id: "visitor-001",
    propertyId: "prop-001",
    sessionId: "session-001",
    email: "visitor1@email.com",
    name: "Michael Chen",
    phone: "+1 (555) 111-2222",
    visitedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    duration: 15.3,
    scenesViewed: ["scene-001", "scene-002", "scene-003"],
    hotspotClicks: 5,
    measurements: 2,
    leadQuality: "hot",
    deviceType: "desktop",
    referralSource: "google",
    sceneEngagement: {
      "scene-001": {
        sceneId: "scene-001",
        viewCount: 1,
        dwellTime: 45,
        hotspotInteractions: { "hotspot-001": 1, "hotspot-002": 1 },
      },
    },
  },
  {
    id: "visitor-002",
    propertyId: "prop-001",
    sessionId: "session-002",
    visitedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    duration: 9.2,
    scenesViewed: ["scene-001", "scene-003"],
    hotspotClicks: 3,
    measurements: 1,
    leadQuality: "warm",
    deviceType: "mobile",
    referralSource: "facebook",
  },
  {
    id: "visitor-003",
    propertyId: "prop-002",
    sessionId: "session-003",
    visitedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    duration: 7.5,
    scenesViewed: ["scene-004", "scene-006"],
    hotspotClicks: 2,
    measurements: 0,
    leadQuality: "cold",
    deviceType: "desktop",
    referralSource: "email",
  },
]

export const mockCaptureServices: CaptureService[] = [
  {
    id: "capture-001",
    propertyId: "prop-001",
    clientName: "Robert Williams",
    clientEmail: "robert@email.com",
    clientPhone: "+1 (555) 555-5555",
    propertyAddress: "789 Maple Drive, Los Angeles, CA 90001",
    serviceType: "premium",
    status: "scheduled",
    scheduledDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    assignedTechnicianId: "tech-001",
    notes: "Luxury property, needs 360° coverage",
    createdAt: new Date(),
  },
]

export const mockFloorPlans: FloorPlan[] = [
  {
    id: "floor-001",
    name: "Penthouse Floor Plan",
    imageUrl: "/floor-plan-layout.jpg",
    scale: 1,
    rooms: [
      {
        id: "room-001",
        name: "Living Room",
        x: 50,
        y: 30,
        width: 200,
        height: 150,
        sceneId: "scene-001",
        color: "#3b82f6",
        dimensions: "20ft x 15ft",
      },
      {
        id: "room-002",
        name: "Master Bedroom",
        x: 300,
        y: 30,
        width: 150,
        height: 120,
        sceneId: "scene-002",
        color: "#8b5cf6",
        dimensions: "15ft x 12ft",
      },
      {
        id: "room-003",
        name: "Kitchen",
        x: 50,
        y: 220,
        width: 180,
        height: 140,
        sceneId: "scene-003",
        color: "#ec4899",
        dimensions: "18ft x 14ft",
      },
    ],
  },
  {
    id: "floor-002",
    name: "Family Home Floor Plan",
    imageUrl: "/family-home-floor-plan.jpg",
    scale: 1,
    rooms: [
      {
        id: "room-101",
        name: "Foyer",
        x: 40,
        y: 40,
        width: 160,
        height: 120,
        sceneId: "scene-004",
        color: "#22c55e",
        dimensions: "12ft x 10ft",
      },
      {
        id: "room-102",
        name: "Living Room",
        x: 220,
        y: 40,
        width: 220,
        height: 180,
        sceneId: "scene-005",
        color: "#0ea5e9",
        dimensions: "18ft x 14ft",
      },
      {
        id: "room-103",
        name: "Backyard",
        x: 100,
        y: 240,
        width: 300,
        height: 200,
        sceneId: "scene-006",
        color: "#f97316",
        dimensions: "30ft x 20ft",
      },
    ],
  },
]

export const mockBookingSlots: BookingSlot[] = [
  {
    id: "slot-001",
    propertyId: "prop-001",
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    time: "10:00 AM",
    duration: 60,
    available: true,
  },
  {
    id: "slot-002",
    propertyId: "prop-001",
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    time: "2:00 PM",
    duration: 60,
    available: true,
  },
  {
    id: "slot-003",
    propertyId: "prop-001",
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    time: "10:00 AM",
    duration: 60,
    available: false,
    bookedBy: "John Smith",
  },
  {
    id: "slot-004",
    propertyId: "prop-002",
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    time: "1:00 PM",
    duration: 45,
    available: true,
  },
]

export const mockPropertyMerges: PropertyMerge[] = [
  {
    id: "merge-001",
    name: "Downtown Complex",
    properties: ["prop-001", "prop-002"],
    floorOrder: ["prop-001", "prop-002"],
    createdAt: new Date(),
  },
]

export const mockCrossPlatformShares: CrossPlatformShare[] = [
  {
    propertyId: "prop-001",
    platforms: {
      googleStreetView: true,
      vrbo: true,
      realtorCom: true,
      zillow: false,
      facebook: true,
      twitter: true,
      linkedin: false,
    },
    shareLinks: {
      googleStreetView: "https://www.google.com/maps/...",
      vrbo: "https://www.vrbo.com/...",
      realtorCom: "https://www.realtor.com/...",
    },
  },
  {
    propertyId: "prop-002",
    platforms: {
      googleStreetView: true,
      vrbo: false,
      realtorCom: true,
      zillow: true,
      facebook: true,
      twitter: false,
      linkedin: true,
    },
    shareLinks: {
      googleStreetView: "https://www.google.com/maps/...",
      realtorCom: "https://www.realtor.com/...",
      zillow: "https://www.zillow.com/...",
    },
  },
]

export const mockWooCommerceProducts: WooCommerceProduct[] = [
  {
    id: "product-001",
    propertyId: "prop-001",
    name: "Smart Lighting Package",
    price: 499,
    sku: "SL-500",
    image: "/open-concept-living-area.jpg",
    hotspotId: "hotspot-002",
  },
  {
    id: "product-002",
    propertyId: "prop-002",
    name: "Outdoor Furniture Set",
    price: 899,
    sku: "OF-899",
    image: "/backyard-with-pool.png",
    hotspotId: "hotspot-008",
  },
]

export const mockModelAssets: Model3DAsset[] = [
  {
    id: "model-001",
    propertyId: "prop-001",
    name: "Living Room Furniture",
    url: "https://models.baladshelter.com/living-room.glb",
    format: "glb",
    sceneId: "scene-001",
    scale: 1,
  },
  {
    id: "model-002",
    propertyId: "prop-002",
    name: "Backyard Landscaping",
    url: "https://models.baladshelter.com/backyard.glb",
    format: "glb",
    sceneId: "scene-006",
    scale: 1,
  },
]

export const mockSceneTypeConfigs: SceneTypeConfig[] = [
  {
    id: "scene-type-001",
    propertyId: "prop-001",
    sceneId: "scene-001",
    type: "equirectangular",
    imageUrl: "/luxury-penthouse-living-room-360.jpg",
    description: "Main living area captured in 8K",
  },
  {
    id: "scene-type-002",
    propertyId: "prop-002",
    sceneId: "scene-005",
    type: "sphere",
    imageUrl: "/open-concept-living-room.jpg",
    description: "Spherical panorama of living area",
  },
]

export const mockTechnicians: TechnicianProfile[] = [
  {
    id: "tech-001",
    name: "Laura Mendes",
    email: "laura.mendes@votex360.com",
    phone: "+1 (555) 777-8899",
    specialization: "premium",
    availability: [new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)],
    completedJobs: 48,
    rating: 4.8,
  },
  {
    id: "tech-002",
    name: "Ethan Patel",
    email: "ethan.patel@votex360.com",
    phone: "+1 (555) 222-1188",
    specialization: "vr",
    availability: [new Date(Date.now() + 4 * 24 * 60 * 60 * 1000)],
    completedJobs: 36,
    rating: 4.7,
  },
]

export const mockBrandingSettings: Record<string, CSSCustomization> = {
  "prop-001": {
    propertyId: "prop-001",
    customCSS: ".tour-player { background: radial-gradient(circle at top, #0f172a, #020617); }",
    whiteLabel: false,
    removeBranding: false,
    customDomain: "penthouse.baladshelter.com",
  },
  "prop-002": {
    propertyId: "prop-002",
    customCSS: ".property-card { border-radius: 24px; }",
    whiteLabel: true,
    removeBranding: false,
    customDomain: "suburbanhomes.baladshelter.com",
  },
}
